# Generated by Django 5.0.6 on 2024-05-13 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20230516_0220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='kyc',
            options={'ordering': ['-date']},
        ),
    ]
